### ISSUE TITLE
enrich variables like https://github.com/edonet/vscode-command-runner

### ISSUE THREAD

**Issue by xieofxie** [AdrianWilczynski/RunTerminalCommand#1]
It is a great extension but if we could support Predefined Variable like that extension it will be even greater XD

**Comment by AdrianWilczynski** [comment]
Hi, I'm honestly not really using this extension myself so I kinda consider it a done project and probably won't be adding any features.

**Comment by xieofxie** [comment]
Oh, thanks for replying. I would just fork and make one myself then
